######################################################################
# Automatically generated by qmake (2.01a) So. Dez 27 08:27:02 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . src
INCLUDEPATH += .

# Input
SOURCES += src/main.cpp \
	src/db.cpp \
    src/mega_tray.cpp \
    src/megatag.cpp

HEADERS += \
	src/db.h \
    src/mega_tray.h \
    src/megatag.h \
    src/graph.h

OTHER_FILES += src/CMakeLists.txt

